name: Update News Data

on:
  schedule:
    # Run daily at 5:00 AM UTC (12:00 AM EST)
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          echo "Installed packages:"
          pip list

      - name: Check API key
        run: |
          if [ -z "$PERPLEXITY_API_KEY" ]; then
            echo "WARNING: PERPLEXITY_API_KEY is not set"
          else
            echo "PERPLEXITY_API_KEY is set (length: ${#PERPLEXITY_API_KEY})"
            # Show first 5 and last 5 characters for verification (without revealing the full key)
            echo "Key preview: ${PERPLEXITY_API_KEY:0:5}...${PERPLEXITY_API_KEY: -5}"
          fi
        env:
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}

      - name: Test API key connection
        env:
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
        run: |
          if [ -z "$PERPLEXITY_API_KEY" ]; then
            echo "Skipping API test - no key available"
          else
            echo "Testing API key..."
            python test_api.py
          fi

      - name: Run backend script to fetch news data
        env:
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
        run: |
          echo "Running backend script..."
          python backend.py
          echo "Backend script completed"
          echo "Contents of data directory:"
          ls -la data/

      - name: Debug data files
        run: |
          echo "All healthcare data files:"
          ls -1 data/*-healthcare.json 2>/dev/null || echo "No healthcare files found"
          echo "Filtered healthcare data files (no test/sample):"
          ls -1 data/*-healthcare.json 2>/dev/null | grep -v test | grep -v sample || echo "No filtered healthcare files found"
          echo "All general data files:"
          ls -1 data/*-general.json 2>/dev/null || echo "No general files found"
          echo "Filtered general data files (no test/sample):"
          ls -1 data/*-general.json 2>/dev/null | grep -v test | grep -v sample || echo "No filtered general files found"

      - name: Update data index
        run: |
          # Create index.json with available files (excluding test files and prioritizing newest)
          echo "{" > data/index.json
          echo "  \"healthcare\": [" >> data/index.json
          # List all healthcare files, exclude test/sample files, sort by date (newest first), take top 5
          FILES=$(ls -1 data/*-healthcare.json 2>/dev/null | grep -v test | grep -v sample | sort -r | head -n 5)
          if [ -n "$FILES" ]; then
            echo "$FILES" | sed 's/data\///' | sed 's/.*/    "&",/' | sed '$ s/,$//' >> data/index.json
          fi
          echo "  ]," >> data/index.json
          echo "  \"general\": [" >> data/index.json
          # List all general files, exclude test/sample files, sort by date (newest first), take top 5
          FILES=$(ls -1 data/*-general.json 2>/dev/null | grep -v test | grep -v sample | sort -r | head -n 5)
          if [ -n "$FILES" ]; then
            echo "$FILES" | sed 's/data\///' | sed 's/.*/    "&",/' | sed '$ s/,$//' >> data/index.json
          fi
          echo "  ]" >> data/index.json
          echo "}" >> data/index.json
          echo "Updated index.json:"
          cat data/index.json

      - name: Commit and push updated files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/
          git diff --staged --quiet || (git commit -m "Update news data ($(date +'%Y-%m-%d'))" && git push) || echo "No changes to commit"